@startuml
participant APPClient as APP
participant APIServer as SERVER


=== 2-STEP MODEL ==

== Trigger Purchase ==

APP -> SERVER: request to createPurchase (payable)
SERVER --> APP: 201 Purchase Created (payable, id, status)

== Payment preparation ==

APP -> SERVER : request to preparePayment (purchase_id)
alt server accept request
SERVER --> APP : 200 OK - payment is prepared
else server denied request
SERVER --> APP : payment preparation request failed
end

== Payment confirmation ==

APP -> SERVER : request to confirmPayment (purchase_id)
alt server accept request
SERVER --> APP : 202 Accepted - payment is charged (confirmed)
else server denied request
SERVER --> APP : payment confirmation request failed
end

== Payment cancellation ==

opt 
APP -> SERVER : request to cancelPayment (purchase_id)
alt server accept request
SERVER --> APP : 202 Accepted - payment is cancelled (released)
else server denied request
SERVER --> APP : payment cancellation request failed - PONR reached
end
end

== Purchase Consultation (anytime) ==
APP -> SERVER : request to getPurchaseInfo (purchase_id)
SERVER --> APP : 200 OK (payable, id, status)

@enduml
