@startuml Open Mobile Alliance transactions/amount
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class Payment <<Pivot>> {
    <b>paymentId</b>: String
    <b>paymentCreationDate</b>: Datetime
    paymentDate: Datetime
}

class AmountTransaction  {
    <b>phoneNumber</b>: String 
    clientCorrelator: String
    <b>referenceCode</b>: String
    <b>transactionOperationStatus</b>: String
    resourceURL: String
    serverReferenceCode : String
    }

Payment --> "1,1" AmountTransaction: amountTransaction

class TransactionOperationStatus <<Enumeration>> {
    Charged
    Refunded
    Reserved
    Released
    Denied 
    Refused 
    Processing
}

class Webhook {
    <b>notificationUrl</b>: String
    notificationAuthToken : String
}

Payment --> "0,1" Webhook: webhook


class PaymentAmountForCharge {
}

class ChargingInformation {
    <b>amount</b>: Number
    <b>currency</b>: String
    <b>description</b>: String
    isTaxIncluded: Boolean
    TaxAmount: Number

}

class ChargingMetaData {
    merchantName: String
    merchantIdentifier: String
    fee: number
    purchaseCategoryCode: String
    channel: String
    serviceId: String
    productId: String
}


class PaymentDetails {
}

class PaymentItem {
    <b>amount</b>: Number
    <b>currency</b>: String
    <b>description</b>: String
    isTaxIncluded: Boolean
    TaxAmount: Number
}

PaymentDetails --> "1,*" PaymentItem : paymentItem

AmountTransaction --> "1,1" PaymentAmountForCharge : <b>paymentAmount</b>

PaymentAmountForCharge --> "1,1" ChargingInformation : <b>chargingInformation</b>
PaymentAmountForCharge --> "0,1" ChargingMetaData : chargingMetaData


PaymentAmountForCharge --> "0,1" PaymentDetails: paymentDetails

AmountTransaction .left. TransactionOperationStatus

@enduml
